# -*- coding: utf-8 -*-
"""data_processor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvxsoO2cVlT6CTDa9PtJ5Ms7iwrMY28s
"""

import pandas as pd

df = pd.read_csv("data_output.csv")

#Transformation simple
df["temp_fahrenheit"] = df["temperature"] * 9/5 + 32

#Nettoyage exemple
df = df[df["humidity"] > 30]

print(df.head())

df.to_csv("processed_data.csv", index=False)