# -*- coding: utf-8 -*-
"""data_producer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPQt4FuU_t_XreOewPFX5fpNnHX5ptiT
"""

import random
import time
import csv

def generate_data():
  return {
      "temperature": random.randint(-10, 35),
      "humidity": random.randint(20, 100)
  }

with open("data_output.csv", mode="w", newline="") as file:
  writer = csv.DictWriter(file, fieldnames=["temperature", "humidity"])
  writer.writeheader()

  for _ in range(20):
    data = generate_data()
    writer.writerow(data)
    print("Generated:", data)
    time.sleep(1)